### PR TITLE
Informational window, how to setup radio before upload new firmware

### PR DESCRIPTION
**Pull request by sp9usb**
Many peoples are confused how to setup the radio before firmware upload to radio (especially when they rarely update the software). So, I created the information form before upload the new firmware from the CPS.

Below the animated gif presenting the feature:
https://imgur.com/yNxWVP4

@rogerclarkmelbourne what do you think about it solution? At this moment, I have just only information about GD77 setup to firmware upload. If/when I found the information about Baofeng's firmware upload setup, I will add this information with pictures in new pull-request. 

73! de SP9USB

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I will try to test it when I get some free time.

**Comment by rogerclarkmelbourne** [comment]
Sorry, I see some problems with this, because you show selecting different radio types but always show the buttons to press on the GD-77 in the animation.

On the RD-5R / DM-5R the buttons are either side of the PTT, not both below the PTT.

I think its only necessary to show an image of which buttons to press on each individual radio, rather than showing that they can download and update or select a file they have already downloaded.

I'll ask the graphic designers on the opengd77 forum if they can create some graphics for this.

**Comment by sp9usb** [comment]
Hi Roger (@rogerclarkmelbourne),

the information window is just only shown when we will choose GD77 or GD77S. This logic is written on the switch in `OnShown` method (https://github.com/rogerclarkmelbourne/OpenGD77CPS/pull/24/files#diff-081c09458fffca5e5f949e70d2189d3cR20).

At this moment, I just only prepared images for GD77. I'm not graphic, so I will be very happy If any experienced graphic designer from opengd77 forum help me and will prepare pictures for each TRX with buttons which shall be press to start upload new firmware. Then I will could show the properly images for specific TRX. In my opinion, that would be greate.

Roger, what do you think about information label? The information: "Before starting upload firmware, click the buttons and turn on the radio." is ok in your opinion? I created generic information for all TRX, but if you think each TRX should have specific information label in window, let me known, please :-).

@Neon22, could you help me to create images for each supported TRX in OpenGD77CPS? Please. I can see that you are very involved in creating graphics for the project.

Thanks in advance,
Kamil - SP9USB

**Comment by Neon22** [comment]
Hi Kamil,
I added a PR trying to address the core problem you are aiming at.
Its not as sophisticated as yours.
I think the problem is that the docs are uptodate in the dev branch - where there is already a section (under installation) addressing how to do firmware and CPS updates BUT people are still looking at the primary Master Branch docs by default.
When Roger decides it's time then Master will be updated.
So please check the development branch and the proposed PR to address firmware and backup procedure and let me know what you think.

The gif could be good but has to work in the md, pdf, and html doc pages.
I think the md is what active people check at this stage of development but the PDF will be the thing people download and print. Which is why I constructed the Cheatsheets. (They have a note on them about firmware uploading.)

**Comment by rogerclarkmelbourne** [comment]
FYI.
I had to spend most of the weekend sorting out other problems and features on the firmware, so I won't have time to look at this again until next weekend.

**Comment by rogerclarkmelbourne** [comment]
Sorry, but I don't think this PR is practical. 

It would require the animation to be recreated if there are any changes to the functionality.

There are plenty of sources of information on the web that explains how to update the firmware.

**Pull request closed without merging**
