### PR TITLE
Don't trim the boot lines.

### PR DESCRIPTION
**Pull request by f1rmb**
Fix Linux csproj

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I'm not too sure how this change got into the code.
It was in change of the entire file, from what i can see in the commit history.


This PR seems to have a change to the project file, something to do with catalan and chinese language files, which you may not have meant to commit. ????

**Comment by f1rmb** [comment]
:-D
That's the Linux project file, not the Windows one. Those helpfiles aren't available anymore, so I get errors when compiling. This doesn't have any impact on the Window build system.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
OK.

**Comment by f1rmb** [comment]
Ahh, eating, what a waste of time :-)

**Comment by f1rmb** [comment]
Hi Roger,

  Could you merge it ?

Cheers.
---
Daniel

**Comment by rogerclarkmelbourne** [comment]
Yes..  I have eventually merged it

**Comment by f1rmb** [comment]
Hi Roger,

Thanks ;)

Cheers.
...
Daniel

**Pull request merged**
