### PR TITLE
Limit OscRef to 10bits value.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I thought this was a 2 byte value.

Why are you limiting it to 1023 ? Or is there something in the C6000 doc that says this is a 10 bit value.

If it needs to be 10 bit, then both the UHF and VHF need to change

**Comment by f1rmb** [comment]
As far as I can see in the code, it's made of two bytes, 0x47 and 0x48, but 0x48 is the upper 2 bits.

**Comment by f1rmb** [comment]
Err, about the Vhf/Uhv, the calibration object use 'Vhf' in it's name, but that's wrong, there is two instances of that object, one for each band ;-)

**Comment by rogerclarkmelbourne** [comment]
I have just pushed a change to add a feature to save the calibration data to a file

But it has shown a bug

If I open the file and then re-save it, 3 bytes are different

0x4A
0xB9 and 
0xBA

I don't know what values these address control

**Comment by rogerclarkmelbourne** [comment]
OK. I see Colin's data


  | 0x48 | R/W | Two_Point_Bias |   | Bit7 | FSK Error Output Enable
-- | -- | -- | -- | -- | -- | --
  |   |   |   |   | Bit6-Bit2 | Reserved
  |   |   |   |   | Bit1-Bit0 | High 2 bits of Modulation   Offset

**Comment by f1rmb** [comment]
BTW. I've raised a small PR in the FW, about masking the 5 reserved bits about this byte.

**Comment by rogerclarkmelbourne** [comment]
Umm.

I think we'll need to double check the register data. Because the ideal value is 1000 and for my DM-1801 I need a much higher value to move it to the correct frequency.


Perhaps there is some other register which also controls the VCTCXO

I noticed in the firmware, that Kai also sets another register for the frequency adjustment, but he has a comment saying the output is not connected, because its a differential output, but only one side of the differential is shown in the schematic

But perhaps the schematic is wrong

**Comment by f1rmb** [comment]
Okay. What kind of higher value ?

**Comment by rogerclarkmelbourne** [comment]
Sorry. I forgot about this PR.

I've now tested and merged it.

**Comment by f1rmb** [comment]
;-) No problem.

**Pull request merged**
