### PR TITLE
Replace hardcoded backslashes with System.IO.Path.DirectorySeparatorChar, which is portable.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK.

BTW. Did you try replacing with "/".  I find now that often I can use "/" on windows and it works OK.

I guess I should try that in the CPS.

**Comment by rogerclarkmelbourne** [comment]
Actually. Your solution is probably better than using / on both platforms.

BTW. I did not externalise some of the new language strings in the CPS yet.

I will need to add it to my ToDo list

**Comment by f1rmb** [comment]
No, I didn't.
I know Win7+ supports '/' as path separator (and convert that on the fly), but I've just done what I'm usually doing when using wxWidgets, at least it's handled by the toolkit/framework ;-)

**Comment by rogerclarkmelbourne** [comment]
OK.

I Windows 7 and later seems to also be able to handle mixed / and \ in the same path, but the DotNet API functions return paths as \

Anyway, I'll merge the code and test it later.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I just tested it

**Pull request merged**
